export enum CapcaitorEnv {
    REACT_CAPACITOR_APP_NAME = '',
    REACT_CAPACITOR_APP_ID = '',

    REACT_CAPACITOR_STAGING_WEB_URL = '',
    REACT_CAPACITOR_STAGING_ALLOW_NAV_URL = '',

    REACT_CAPACITOR_PROD_WEB_URL = '',
    REACT_CAPACITOR_PROD_ALLOW_NAV_URL = '',
}